# Questions 1:

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

val = np.arange(2, 51, 3)

print(val)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:

Accept two lists of 5 elements each from the user.

Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
# --importing numpy--

lst1 = eval(input())
lst2 = eval(input())

val1 = np.array(lst1)
val2 = np.array(lst2)

x = np.concatenate((val1, val2))
print("Concatenated Arrays: ", x)

y = np.sort(x)
print("Sorted Arrays: ", y)

[25,35,46,24,14]
[24,56,34,23,76]
Concatenated Arrays:  [25 35 46 24 14 24 56 34 23 76]
Sorted Arrays:  [14 23 24 24 25 34 35 46 56 76]


# Questions 3:

Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
# --importing numpy--

val = np.arange(8).reshape((2, 4))
print(val)

print("Dimension of Array: ", val.ndim)
print("Size of Array: ", val.size)

[[0 1 2 3]
 [4 5 6 7]]
Dimension of Array:  2
Size of Array:  8


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

Hint: np.newaxis, np.expand_dims

In [4]:
# --importing numpy--

val = np.array([34, 52, 31, 12])
print("1D Array: ", val.shape)

print("\n1D Array Converted to 2D Array\n")
val1 = np.expand_dims(val, axis=0)
print("In Row Vector: ", val1.shape)

val1 = np.expand_dims(val, axis=1)
print("In Column Vector: ", val1.shape)

1D Array:  (4,)

1D Array Converted to 2D Array

In Row Vector:  (1, 4)
In Column Vector:  (4, 1)


# Questions 5:

Consider two square numpy arrays. Stack them vertically and horizontally.

Hint: Use vstack(), hstack()

In [5]:
# --importing numpy--

val1 = np.array([17,24,33])
val2 = np.array([44,75,26])

print('Horizontal:\n', np.hstack((val1, val2)))
print('Vertical:\n', np.vstack((val1, val2)))

Horizontal:
 [17 24 33 44 75 26]
Vertical:
 [[17 24 33]
 [44 75 26]]


# Questions 6:

How to get unique items and counts of unique items?

In [6]:
# --importing numpy--

val = [1,4,57,4,78,1,24,88,78,56,88]

unique, count = np.unique(val, return_counts=True)

print("Unique Items: ", unique)
print("Count of Unique Items: ", count)

Unique Items:  [ 1  4 24 56 57 78 88]
Count of Unique Items:  [2 2 1 1 1 2 2]
